// component-data.js — the structured component system for /engineering.
//
// One source of truth for the machine's component architecture: groups,
// components, one-sentence descriptions, visual priority, focus ranges, and
// the on-screen label set. The reference for realism is a thin FANLESS
// ultrabook (thin body, big flat battery, dense logic board, passive thermal
// stack, port boards at the edges). No brand names, no fake specs.
//
// Owner-directed realism pass (2026-07-02): this supersedes the generic
// fan/heat-pipe/SO-DIMM architecture of 05 §5.2 — the node names below are
// now the bind contract for any future production GLB.
//
// Voice rules (D-006 still binding): one sentence per description, plain,
// specific, no buzzwords, no invented statistics, no exclamation marks.

export const GROUPS = [
  { id: 'display-assembly', title: 'Display assembly' },
  { id: 'top-case', title: 'Top case / keyboard deck' },
  { id: 'battery-system', title: 'Battery system' },
  { id: 'logic-board', title: 'Logic board' },
  { id: 'thermal-system', title: 'Passive thermal system' },
  { id: 'io-boards', title: 'Port and I/O boards' },
  { id: 'audio-system', title: 'Audio system' },
  { id: 'lower-case', title: 'Lower case / chassis' },
];

// visualPriority: 'hero' (gets a beat/card), 'focus' (gets a label moment),
// 'detail' (visible geometry, named here, no dedicated moment).
// focusRange: [in, out] in timeline progress where the part is the subject.
// node: the scene-graph name that carries or anchors it (bind contract).
export const COMPONENTS = [
  // ---- Group 1: display assembly ----
  { id: 'display-assembly', group: 'display-assembly', node: 'display_assembly',
    title: 'Display assembly', visualPriority: 'hero', focusRange: [0.105, 0.238],
    description: 'The whole display lifts away as one engineered unit: shell, glass, panel, camera, and hinges.' },
  { id: 'display-shell', group: 'display-assembly', node: 'display_shell',
    title: 'Aluminum display shell', visualPriority: 'detail',
    description: 'The outer shell gives the display its structure while keeping the panel thin and rigid.' },
  { id: 'display-glass', group: 'display-assembly', node: 'display_glass',
    title: 'Display glass', visualPriority: 'detail',
    description: 'A thin glass surface protects the panel and catches subtle room reflections.' },
  { id: 'display-panel', group: 'display-assembly', node: 'display_panel',
    title: 'Display panel', visualPriority: 'detail',
    description: 'The image layer sits behind the glass and forms the visible display surface.' },
  { id: 'camera-area', group: 'display-assembly', node: 'display_camera',
    title: 'Camera and sensor area', visualPriority: 'detail',
    description: 'A compact camera and sensor strip sits centered along the top edge of the display.' },
  { id: 'display-flex', group: 'display-assembly', node: 'display_flex',
    title: 'Display flex cable', visualPriority: 'detail',
    description: 'A thin ribbon cable carries image and camera data through the hinge area.' },
  { id: 'hinge-barrels', group: 'display-assembly', node: 'hinge_barrel_l',
    title: 'Hinge barrels', visualPriority: 'focus', focusRange: [0.136, 0.238],
    description: 'Precision hinge barrels control the opening motion and route hidden cables into the body.' },
  { id: 'antenna-regions', group: 'display-assembly', node: 'display_antenna',
    title: 'Antenna regions', visualPriority: 'detail',
    description: 'Wireless antennas hide around the display assembly where signal paths stay clear of the metal body.' },

  // ---- Group 2: top case / keyboard deck ----
  { id: 'top-case', group: 'top-case', node: 'top_case',
    title: 'Aluminum top case', visualPriority: 'hero', focusRange: [0.205, 0.388],
    description: 'The machined upper shell supports the keyboard, trackpad, battery, and board mounting points.' },
  { id: 'keyboard-membrane', group: 'top-case', node: 'keyboard_membrane',
    title: 'Keyboard membrane', visualPriority: 'detail',
    description: 'A thin input layer sits under the keycaps and routes keystrokes back to the logic board.' },
  { id: 'keycap-field', group: 'top-case', node: 'keycap_field',
    title: 'Keycap field', visualPriority: 'detail',
    description: 'The visible keyboard surface stays shallow, precise, and tightly integrated into the deck.' },
  { id: 'power-button', group: 'top-case', node: 'power_button',
    title: 'Fingerprint power button', visualPriority: 'detail',
    description: 'The power button doubles as a secure identity sensor and connects back to the board through a small flex path.' },
  { id: 'keyboard-backlight', group: 'top-case', node: 'key_backlight',
    title: 'Keyboard backlight layer', visualPriority: 'detail',
    description: 'A thin light guide spreads illumination under the key field without adding height.' },
  { id: 'trackpad-glass', group: 'top-case', node: 'trackpad_glass',
    title: 'Trackpad glass surface', visualPriority: 'focus', focusRange: [0.250, 0.388],
    description: 'A glass touch surface sits flush in the palm rest and catches a softer reflection than the aluminum.' },
  { id: 'trackpad-assembly', group: 'top-case', node: 'trackpad_assembly',
    title: 'Force trackpad assembly', visualPriority: 'detail',
    description: 'A pressure-sensing assembly below the glass simulates click feedback without a moving hinge.' },
  { id: 'trackpad-flex', group: 'top-case', node: 'trackpad_flex',
    title: 'Trackpad flex cable', visualPriority: 'detail',
    description: 'A short ribbon cable connects the trackpad assembly to the logic board.' },

  // ---- Group 3: battery system ----
  { id: 'battery-cells', group: 'battery-system', node: 'battery_cells',
    title: 'Battery cell array', visualPriority: 'focus', focusRange: [0.797, 0.862],
    description: 'Flat lithium cells fill most of the internal volume, using the thin body as efficiently as possible.' },
  { id: 'battery-bms', group: 'battery-system', node: 'battery_bms',
    title: 'Battery management board', visualPriority: 'detail',
    description: 'A narrow control board monitors charging, safety, and power delivery across the cell pack.' },
  { id: 'battery-tabs', group: 'battery-system', node: 'battery_cells',
    title: 'Battery pull tabs', visualPriority: 'detail',
    description: 'Subtle pull tabs hint at real service access without turning the scene into a repair manual.' },
  { id: 'battery-cable', group: 'battery-system', node: 'battery_bms',
    title: 'Battery cable', visualPriority: 'detail',
    description: 'A flat cable routes stored power from the cells into the logic board.' },
  { id: 'adhesive-zones', group: 'battery-system', node: 'battery_cells',
    title: 'Cell adhesive zones', visualPriority: 'detail',
    description: 'Muted adhesive strips hold the cells flat against the lower shell.' },

  // ---- Group 4: logic board ----
  { id: 'logic-board', group: 'logic-board', node: 'logic_board',
    title: 'Logic board', visualPriority: 'hero', focusRange: [0.693, 0.797],
    description: 'The dense heart of the machine carries the processor, memory, storage, and power on one compact board.' },
  { id: 'main-processor-package', group: 'logic-board', node: 'soc_package',
    title: 'Main processor package', visualPriority: 'focus', focusRange: [0.470, 0.612],
    description: 'The central chip combines compute, graphics, media processing, and system control into one compact package.' },
  { id: 'unified-memory', group: 'logic-board', node: 'memory_packages',
    title: 'Unified memory packages', visualPriority: 'focus', focusRange: [0.482, 0.612],
    description: 'Memory packages sit on the processor substrate so active data travels across very short paths.' },
  { id: 'nand-storage', group: 'logic-board', node: 'storage_packages',
    title: 'Storage packages', visualPriority: 'focus', focusRange: [0.494, 0.612],
    description: 'Soldered storage packages hold data directly on the board, saving space inside the thin chassis.' },
  { id: 'storage-controller', group: 'logic-board', node: 'logic_board',
    title: 'Storage controller region', visualPriority: 'detail',
    description: 'A small controller area coordinates reads, writes, and wear leveling across the storage packages.' },
  { id: 'power-management', group: 'logic-board', node: 'logic_board',
    title: 'Power management ICs', visualPriority: 'detail',
    description: 'Power chips regulate battery and adapter input before sending stable voltage to the rest of the system.' },
  { id: 'voltage-regulators', group: 'logic-board', node: 'logic_board',
    title: 'Voltage regulator modules', visualPriority: 'detail',
    description: 'Tiny inductors, capacitors, and regulators smooth power for the processor, memory, and ports.' },
  { id: 'timing-crystal', group: 'logic-board', node: 'logic_board',
    title: 'Clock and timing crystal', visualPriority: 'detail',
    description: 'A tiny timing component keeps the digital systems synchronized.' },
  { id: 'usbc-controller', group: 'logic-board', node: 'logic_board',
    title: 'USB-C controller area', visualPriority: 'detail',
    description: 'A controller region manages high-speed data, charging, and external display signals.' },
  { id: 'audio-controller', group: 'logic-board', node: 'logic_board',
    title: 'Audio controller area', visualPriority: 'detail',
    description: 'A small audio region processes microphone, speaker, and headphone signals.' },
  { id: 'wireless-module', group: 'logic-board', node: 'logic_board',
    title: 'Wireless module region', visualPriority: 'detail',
    description: 'Wireless hardware handles network and short-range communication through antennas routed away from the metal body.' },
  { id: 'b2b-connectors', group: 'logic-board', node: 'logic_board',
    title: 'Board-to-board connectors', visualPriority: 'detail',
    description: 'Low-profile connectors link the board to the keyboard, trackpad, battery, display, ports, and speakers.' },
  { id: 'ribbon-sockets', group: 'logic-board', node: 'logic_board',
    title: 'Ribbon cable sockets', visualPriority: 'detail',
    description: 'Tiny locking sockets secure flat flex cables without wasting internal height.' },
  { id: 'grounding-pads', group: 'logic-board', node: 'logic_board',
    title: 'Grounding pads', visualPriority: 'detail',
    description: 'Metal contact pads tie the board to the chassis for shielding and electrical stability.' },
  { id: 'screw-posts', group: 'logic-board', node: 'logic_board',
    title: 'Screw posts', visualPriority: 'detail',
    description: 'Tiny mounting points hold the board in place and keep it aligned with the chassis.' },
  { id: 'circuit-traces', group: 'logic-board', node: 'logic_board',
    title: 'Circuit traces', visualPriority: 'detail',
    description: 'Fine traces read as subtle etched paths across the board, never as glowing lines.' },

  // ---- Group 5: passive thermal system (fanless — no fan exists) ----
  { id: 'shield-plate', group: 'thermal-system', node: 'shield_plate',
    title: 'Shielding and heat plate', visualPriority: 'hero', focusRange: [0.388, 0.470],
    description: 'A thin shield protects the processor area and helps distribute warmth into the chassis.' },
  { id: 'graphite-sheet', group: 'thermal-system', node: 'graphite_sheet',
    title: 'Graphite heat sheet', visualPriority: 'hero', focusRange: [0.400, 0.482],
    description: 'A thin graphite layer spreads heat sideways through the body without needing a fan.' },
  { id: 'contact-plate', group: 'thermal-system', node: 'shield_plate',
    title: 'Processor contact plate', visualPriority: 'detail',
    description: 'This contact area transfers heat from the chip package into the passive cooling stack.' },
  { id: 'chassis-heat-path', group: 'thermal-system', node: 'lower_case',
    title: 'Chassis heat path', visualPriority: 'detail',
    description: 'The aluminum body itself spreads heat through the lower shell as part of the thermal system.' },

  // ---- Group 6: port and I/O boards ----
  { id: 'usbc-port-board', group: 'io-boards', node: 'port_board_usbc',
    title: 'USB-C port board', visualPriority: 'hero', focusRange: [0.569, 0.717],
    description: 'Compact high-speed ports handle charging, data, and external display output.' },
  { id: 'port-bracket', group: 'io-boards', node: 'port_board_usbc',
    title: 'Port reinforcement bracket', visualPriority: 'detail',
    description: 'A small bracket keeps the ports aligned with the chassis edge after repeated cable use.' },
  { id: 'charge-board', group: 'io-boards', node: 'port_board_charge',
    title: 'Magnetic charge board', visualPriority: 'focus', focusRange: [0.581, 0.717],
    description: 'A small separate board handles the magnetic charging connector and routes power inward.' },
  { id: 'audio-jack-board', group: 'io-boards', node: 'port_board_audio',
    title: 'Headphone jack board', visualPriority: 'focus', focusRange: [0.593, 0.717],
    description: 'A tiny side board carries the analog audio hardware separate from the main logic board.' },
  { id: 'port-flex', group: 'io-boards', node: 'port_board_usbc',
    title: 'Port flex cables', visualPriority: 'detail',
    description: 'Thin cables link the side-mounted port boards back to the logic board.' },

  // ---- Group 7: audio system ----
  { id: 'speaker-left', group: 'audio-system', node: 'speaker_l',
    title: 'Left speaker chamber', visualPriority: 'focus', focusRange: [0.809, 0.862],
    description: 'A slim acoustic chamber uses available body volume to deepen the sound.' },
  { id: 'speaker-right', group: 'audio-system', node: 'speaker_r',
    title: 'Right speaker chamber', visualPriority: 'detail',
    description: 'The matching chamber balances stereo output across the body.' },
  { id: 'speaker-driver', group: 'audio-system', node: 'speaker_l',
    title: 'Speaker driver', visualPriority: 'detail',
    description: 'A compact driver produces sound through a thin opening in the chassis.' },
  { id: 'microphone-array', group: 'audio-system', node: 'logic_board',
    title: 'Microphone array', visualPriority: 'detail',
    description: 'Small microphone openings route voice input into the audio system.' },

  // ---- Group 8: lower case / chassis ----
  { id: 'lower-shell', group: 'lower-case', node: 'lower_case',
    title: 'Lower aluminum shell', visualPriority: 'focus', focusRange: [0.797, 0.862],
    description: 'The bottom shell protects the internal parts and gives the device its final rigid shape.' },
  { id: 'internal-ribs', group: 'lower-case', node: 'lower_case',
    title: 'Internal ribs', visualPriority: 'detail',
    description: 'Subtle ribs strengthen the thin shell without adding unnecessary thickness.' },
  { id: 'screw-bosses', group: 'lower-case', node: 'lower_case',
    title: 'Screw bosses', visualPriority: 'detail',
    description: 'Small mounting posts align the lower shell with the top case and the internal boards.' },
  { id: 'foot-inserts', group: 'lower-case', node: 'foot_inserts',
    title: 'Rubber foot inserts', visualPriority: 'detail',
    description: 'Low-profile feet lift the body slightly from the surface and protect the aluminum.' },
  { id: 'grounding-contacts', group: 'lower-case', node: 'lower_case',
    title: 'Grounding contacts', visualPriority: 'detail',
    description: 'Small metal contact areas connect the shell to the internal shielding points.' },
  { id: 'ventless-edge', group: 'lower-case', node: 'lower_case',
    title: 'Ventless edge geometry', visualPriority: 'detail',
    description: 'A clean, ventless edge profile reinforces the fanless design and keeps the body minimal.' },
];

// ---- The on-screen label set (chips). in/out are timeline addresses; the
// full set re-enters at the B8 tableau as the finished diagram. side is the
// fixed screen side (+1 right / −1 left); re is the tableau stagger slot.
// Never more than three labels share a window (visual detail rule).
export const LABELS = [
  { key: 'display', text: 'Display', anchor: 'display_assembly', move: 'display_assembly', side: 1, inAt: 0.124, out: 0.238, next: 0.136, re: 0 },
  { key: 'hinge', text: 'Hinge', anchor: 'hinge_barrel_l', move: 'display_assembly', side: -1, inAt: 0.136, out: 0.238, next: 0.238, re: 1 },
  { key: 'deck', text: 'Keyboard deck', anchor: 'top_case', move: 'top_case', side: 1, inAt: 0.238, out: 0.388, next: 0.250, re: 2 },
  { key: 'trackpad', text: 'Trackpad', anchor: 'trackpad_glass', move: 'top_case', side: -1, inAt: 0.250, out: 0.388, next: 0.409, re: 3 },
  { key: 'shield', text: 'Shield plate', anchor: 'shield_plate', move: 'shield_plate', side: -1, inAt: 0.409, out: 0.470, next: 0.421, re: 4 },
  { key: 'graphite', text: 'Graphite sheet', anchor: 'graphite_sheet', move: 'graphite_sheet', side: 1, inAt: 0.421, out: 0.482, next: 0.470, re: 5 },
  { key: 'processor', text: 'Processor', anchor: 'soc_package', move: 'logic_board', side: 1, inAt: 0.470, out: 0.612, next: 0.482, re: 6 },
  { key: 'memory', text: 'Memory', anchor: 'memory_packages', move: 'logic_board', side: -1, inAt: 0.482, out: 0.612, next: 0.494, re: 7 },
  { key: 'storage', text: 'Storage', anchor: 'storage_packages', move: 'logic_board', side: -1, inAt: 0.494, out: 0.612, next: 0.612, re: 8 },
  { key: 'ports', text: 'Port boards', anchor: 'port_board_usbc', move: 'port_board_usbc', side: -1, inAt: 0.612, out: 0.717, next: 0.717, re: 9 },
  { key: 'board', text: 'Logic board', anchor: 'logic_board', move: 'logic_board', side: 1, inAt: 0.717, out: 0.797, next: 0.797, re: 10 },
  { key: 'battery', text: 'Battery', anchor: 'battery_cells', move: 'battery_cells', side: 1, inAt: 0.797, out: 0.862, next: 0.809, re: 11 },
  { key: 'speakers', text: 'Speakers', anchor: 'speaker_l', move: 'speaker_l', side: -1, inAt: 0.809, out: 0.862, next: null, re: 12 },
  { key: 'shell', text: 'Lower shell', anchor: 'lower_case', move: 'lower_case', side: -1, inAt: 0.797, out: 0.862, next: 0.809, re: 13 },
];
